notifications:
  email:
    recipients:
    - alexgre@ufl.edu
    on_success: always
    on_failure: always
sudo: required
dist: trusty
language: node_js
node_js:
- 8.7.0
branches:
  only:
  - master
addons:
  chrome: stable
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
  - google-chrome-beta
before_install:
- openssl aes-256-cbc -K $encrypted_292734f88679_key -iv $encrypted_292734f88679_iv
  -in alexgre1.pem.enc -out alexgre1.pem -d
- chmod 600 alexgre1.pem
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install -g @angular/cli
- npm install -g karma
- npm install
- ng build --prod
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu
  $(lsb_release -cs) stable"
- sudo apt-get update
- apt-cache policy docker-ce
- sudo apt-get install -y docker-ce
- sudo docker build -t alexgre/aapp:latest -t alexgre/aapp:1.0 .
#- sudo docker build -t alexgre/aapp:1.0 .
- cat docker_pwd.txt | sudo docker login -u alexgre --password-stdin
- sudo apt-get install ssh
script: ./node_modules/.bin/karma start karma.conf.js --single-run --log-level=DEBUG
after_success:
- sudo docker push alexgre/aapp:latest
- sudo docker push alexgre/aapp:1.0
#- ./test.sh
- ssh -oUserKnownHostsFile=/dev/null -oStrictHostKeyChecking=no -i "alexgre1.pem" ubuntu@ec2-34-201-172-56.compute-1.amazonaws.com /bin/bash << 'EOT'
  Xy123456 | sudo docker login -u alexgre --password-stdin
  sudo docker stop $(docker ps -q --filter ancestor=alexgre/angulardocker1.0)
  sudo docker pull alexgre/aapp
  sudo docker run --rm -d -p 80:80 alexgre/aapp
  EOT
- echo "done"

  # - pip install --user awscli # install aws cli w/o sudo
  # - export PATH=$PATH:$HOME/.local/bin # put aws in the path
  # - eval $(aws ecr get-login --region us-east-1) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
  # - docker tag app_1.0 538225610467.dkr.ecr.us-east-1.amazonaws.com/app:latest
  # - docker push 538225610467.dkr.ecr.us-east-1.amazonaws.com/app:latest
